spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: USER-SERVICE
            uri: lb://USER-SERVICE
            predicates:
              - Path=/users/**
          - id: DEPARTMENT-SERVICE
            uri: lb://DEPARTMENT-SERVICE
            predicates:
              - Path=/department/**
  config:
    import: configserver:http://localhost:8001

server:
  port: 8000
