spring:
  application:
    name: user-service
  datasource:
    password: password
    driver-class-name: org.postgresql.Driver
    username: postgres
    url: jdbc:postgresql://localhost:5432/testDB
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  config:
    import: configserver:http://localhost:8001

server:
  port: 8081
